### Word embeddings practical implimentation

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### SEntences
sent=["I love programming.", "Python is great.", "I enjoy learning new things.",
      "Data science is fascinating.", "I like to solve problems.","I appreciate good code.", "Machine learning is exciting.",
      "I find algorithms interesting.", "I enjoy working with data.", "Programming is a valuable skill.","I love to create software.",
      "I enjoy building applications.", "I like to automate tasks.", "I find coding rewarding.",
      "I appreciate elegant solutions.", "I enjoy debugging code.", "I like to optimize performance.",
      "I find software development fulfilling.", "I enjoy collaborating on projects.", "I like to innovate.",
      "I appreciate clean code.", "I enjoy learning new programming languages.", ]

In [3]:
#Define the vocabulary size
vocab_size=10000



In [4]:
#one hot representation for every word in the sentence
one_hot_repr=[one_hot(words,vocab_size) for words in sent]
one_hot_repr

[[653, 2696, 4507],
 [8469, 9033, 5491],
 [653, 9471, 5371, 2172, 3663],
 [9665, 1314, 9033, 9400],
 [653, 4223, 7354, 939, 8215],
 [653, 8002, 248, 3520],
 [7508, 5371, 9033, 8772],
 [653, 5275, 5253, 2777],
 [653, 9471, 5000, 9908, 9665],
 [4507, 9033, 6634, 4432, 5503],
 [653, 2696, 7354, 6867, 1458],
 [653, 9471, 5337, 7839],
 [653, 4223, 7354, 9967, 7402],
 [653, 5275, 3926, 279],
 [653, 8002, 7120, 3097],
 [653, 9471, 5322, 3520],
 [653, 4223, 7354, 2394, 4936],
 [653, 5275, 1458, 2467, 579],
 [653, 9471, 1430, 5543, 9825],
 [653, 4223, 7354, 9150],
 [653, 8002, 7488, 3520],
 [653, 9471, 5371, 2172, 4507, 6578]]

In [5]:
# Word embedding repreentation for every sentence
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [ ]:
#there are  two type of padding one is pre and other is post
#pre means padding will be added before the sentence and post means padding will be added after the
set_length=10
embedd_docs=pad_sequences(one_hot_repr,maxlen=set_length,padding='post')
embedd_docs

array([[ 653, 2696, 4507,    0,    0,    0,    0,    0,    0,    0],
       [8469, 9033, 5491,    0,    0,    0,    0,    0,    0,    0],
       [ 653, 9471, 5371, 2172, 3663,    0,    0,    0,    0,    0],
       [9665, 1314, 9033, 9400,    0,    0,    0,    0,    0,    0],
       [ 653, 4223, 7354,  939, 8215,    0,    0,    0,    0,    0],
       [ 653, 8002,  248, 3520,    0,    0,    0,    0,    0,    0],
       [7508, 5371, 9033, 8772,    0,    0,    0,    0,    0,    0],
       [ 653, 5275, 5253, 2777,    0,    0,    0,    0,    0,    0],
       [ 653, 9471, 5000, 9908, 9665,    0,    0,    0,    0,    0],
       [4507, 9033, 6634, 4432, 5503,    0,    0,    0,    0,    0],
       [ 653, 2696, 7354, 6867, 1458,    0,    0,    0,    0,    0],
       [ 653, 9471, 5337, 7839,    0,    0,    0,    0,    0,    0],
       [ 653, 4223, 7354, 9967, 7402,    0,    0,    0,    0,    0],
       [ 653, 5275, 3926,  279,    0,    0,    0,    0,    0,    0],
       [ 653, 8002, 7120, 3097,   

In [8]:
#featre representation
dim=10


In [ ]:
set_length

10000

In [13]:

from tensorflow.keras.layers import Embedding
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=set_length))
model.compile(optimizer='adam',loss='mse',metrics=['accuracy'])


d:\GenAi\UdemyCourse\IMDB\IMDB_Movie_Review\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedd_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step


array([[[-0.03979846, -0.00042754,  0.00901643, ..., -0.02785384,
          0.0085482 ,  0.03572762],
        [ 0.02885773,  0.01650939, -0.0119619 , ..., -0.02291697,
         -0.00195092, -0.04640323],
        [ 0.03425237,  0.03828451,  0.0497008 , ...,  0.00723834,
         -0.0320828 ,  0.03914303],
        ...,
        [-0.04207595, -0.03579729,  0.02515293, ..., -0.03061792,
         -0.02307006,  0.0129423 ],
        [-0.04207595, -0.03579729,  0.02515293, ..., -0.03061792,
         -0.02307006,  0.0129423 ],
        [-0.04207595, -0.03579729,  0.02515293, ..., -0.03061792,
         -0.02307006,  0.0129423 ]],

       [[ 0.04298962, -0.03810285, -0.02640588, ..., -0.00837958,
          0.00824455, -0.02460268],
        [-0.01113999, -0.01071645, -0.03554193, ..., -0.02307397,
         -0.02306324, -0.03490034],
        [ 0.00398393, -0.02850868,  0.0154731 , ...,  0.03280493,
          0.00032302,  0.01883698],
        ...,
        [-0.04207595, -0.03579729,  0.02515293, ..., -

In [18]:
model.predict(embedd_docs[0].reshape(1,10))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[[-0.03979846, -0.00042754,  0.00901643, -0.01072101,
         -0.00275441, -0.00064746, -0.04718089, -0.02785384,
          0.0085482 ,  0.03572762],
        [ 0.02885773,  0.01650939, -0.0119619 , -0.01921855,
         -0.02200877,  0.01908144,  0.02516248, -0.02291697,
         -0.00195092, -0.04640323],
        [ 0.03425237,  0.03828451,  0.0497008 , -0.03302759,
         -0.01657081, -0.03908274,  0.01172577,  0.00723834,
         -0.0320828 ,  0.03914303],
        [-0.04207595, -0.03579729,  0.02515293, -0.02363631,
          0.02244438,  0.0041879 , -0.00345731, -0.03061792,
         -0.02307006,  0.0129423 ],
        [-0.04207595, -0.03579729,  0.02515293, -0.02363631,
          0.02244438,  0.0041879 , -0.00345731, -0.03061792,
         -0.02307006,  0.0129423 ],
        [-0.04207595, -0.03579729,  0.02515293, -0.02363631,
          0.02244438,  0.0041879 , -0.00345731, -0.03061792,
         -0.02307006,  0.0129423 ],
        [-0.04207595, -0.03579729,  0.02515293, -0.0